version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: techchallenge_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: oficinadb
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: techchallenge_api
    restart: always
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/oficinadb?schema=public
      - JWT_SECRET=techchallenge_secret_key_2026
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:
