sonar.projectKey=tech-challenge-oficina
sonar.projectName=Tech Challenge Oficina Mecanica
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=src/**/*.spec.ts,test/**/*.ts

sonar.exclusions=src/**/*.spec.ts,test/**,dist/**,coverage/**,node_modules/**,prisma/migrations/**,src/**/*.integration-spec.ts

sonar.coverage.exclusions=src/**/*.module.ts,src/main.ts,src/app.controller.ts,src/app.service.ts,src/**/*.dto.ts,src/**/dtos/**,src/**/dto/**,src/**/*.interface.ts,src/**/contracts/**,src/**/acls/**,src/**/*.swagger.ts,src/**/swaggers/**,src/**/enums/**,src/**/factories/**,src/prisma/**,src/**/in-memory-*.ts,src/**/exceptions/index.ts

sonar.javascript.lcov.reportPaths=combined-coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
