sonar.projectKey=tech-challenge-oficina
sonar.projectName=Tech Challenge Oficina Mecanica
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src
sonar.tests=backend/src,backend/test
sonar.test.inclusions=backend/src/**/*.spec.ts,backend/test/**/*.ts

sonar.exclusions=backend/src/**/*.spec.ts,backend/test/**,backend/dist/**,backend/coverage/**,backend/node_modules/**,backend/prisma/migrations/**,backend/src/**/*.integration-spec.ts

sonar.coverage.exclusions=backend/src/**/*.module.ts,backend/src/main.ts,backend/src/app.controller.ts,backend/src/app.service.ts,backend/src/**/*.dto.ts,backend/src/**/dtos/**,backend/src/**/dto/**,backend/src/**/*.interface.ts,backend/src/**/contracts/**,backend/src/**/acls/**,backend/src/**/*.swagger.ts,backend/src/**/swaggers/**,backend/src/**/enums/**,backend/src/**/factories/**,backend/src/prisma/**,backend/src/**/in-memory-*.ts,backend/src/**/exceptions/index.ts

sonar.javascript.lcov.reportPaths=backend/combined-coverage/lcov.info
sonar.typescript.tsconfigPath=backend/tsconfig.json
