apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "adminpassword"
  JWT_SECRET: "techchallenge_secret_key_2026"
  PASSWORD_SALT: "4a7b1e8f9c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f"
  DATABASE_URL: "postgresql://admin:adminpassword@db-service:5432/oficinadb?schema=public"