import type { Config } from 'jest';

const config: Config = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '../..',
  testRegex: '.*\\.integration-spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@materials/(.*)$': '<rootDir>/src/materials/$1',
    '^@service-orders/(.*)$': '<rootDir>/src/service-orders/$1',
    '^@service-catalog/(.*)$': '<rootDir>/src/service-catalog/$1',
    '^@customer-management/(.*)$': '<rootDir>/src/customer-management/$1',
    '^@access-identity/(.*)$': '<rootDir>/src/access-identity/$1',
    '^@common/(.*)$': '<rootDir>/src/common/$1',
  },
  collectCoverageFrom: [
    'src/**/*.(t|j)s',
    '!src/**/*.spec.ts',
    '!src/**/*.integration-spec.ts',
    '!src/**/*.module.ts',
    '!src/main.ts',
    '!src/app.controller.ts',
    '!src/app.service.ts',
    '!src/**/*.dto.ts',
    '!src/**/dtos/**',
    '!src/**/dto/**',
    '!src/**/*.interface.ts',
    '!src/**/contracts/**',
    '!src/**/acls/**',
    '!src/**/*.swagger.ts',
    '!src/**/swaggers/**',
    '!src/**/enums/**',
    '!src/**/factories/**',
    '!src/prisma/**',
    '!src/**/in-memory-*.ts',
    '!src/**/exceptions/index.ts',
  ],
  coverageDirectory: '<rootDir>/coverage-integration',
  coverageThreshold: {
    global: {
      statements: 0,
      branches: 0,
      functions: 0,
      lines: 0,
    },
    'src/service-orders/infra/repositories/': {
      statements: 70,
      branches: 35,
      functions: 75,
      lines: 70,
    },
    'src/service-orders/infra/services/': {
      statements: 80,
      branches: 70,
      functions: 80,
      lines: 80,
    },
    'src/service-orders/infra/mappers/': {
      statements: 80,
      branches: 70,
      functions: 80,
      lines: 80,
    },
    'src/customer-management/infra/repositories/': {
      statements: 80,
      branches: 60,
      functions: 80,
      lines: 80,
    },
    'src/customer-management/infra/services/': {
      statements: 80,
      branches: 70,
      functions: 80,
      lines: 80,
    },
    'src/materials/infra/repositories/': {
      statements: 80,
      branches: 50,
      functions: 80,
      lines: 80,
    },
    'src/service-catalog/infra/repositories/': {
      statements: 80,
      branches: 70,
      functions: 80,
      lines: 80,
    },
    'src/access-identity/infra/repositories/': {
      statements: 80,
      branches: 70,
      functions: 80,
      lines: 80,
    },
    'src/service-orders/presentation/': {
      statements: 80,
      branches: 70,
      functions: 80,
      lines: 80,
    },
    'src/customer-management/presentation/': {
      statements: 80,
      branches: 70,
      functions: 80,
      lines: 80,
    },
    'src/materials/presentation/': {
      statements: 80,
      branches: 70,
      functions: 80,
      lines: 80,
    },
    'src/service-catalog/presentation/': {
      statements: 80,
      branches: 70,
      functions: 80,
      lines: 80,
    },
    'src/access-identity/presentation/': {
      statements: 80,
      branches: 70,
      functions: 80,
      lines: 80,
    },
    'src/common/filters/': {
      statements: 70,
      branches: 10,
      functions: 80,
      lines: 65,
    },
    'src/common/interceptors/': {
      statements: 80,
      branches: 70,
      functions: 80,
      lines: 80,
    },
  },
};

export default config;
