graph TB
    subgraph Docker
        DB[(PostgreSQL 15)]
        API[NestJS API :3000]
        SONAR[SonarQube :9000]
    end

    subgraph AppModule
        AUTH[AuthModule]
        CLI[ClientsModule]
        VEH[VehiclesModule]
        PARTS[PartsModule]
        SCAT[ServiceCatalogModule]
        SO[ServiceOrdersModule]
        PRISMA[PrismaModule]
    end

    API --> DB
    API --> SONAR
    AUTH --> PRISMA
    CLI --> PRISMA
    VEH --> PRISMA
    PARTS --> PRISMA
    SCAT --> PRISMA
    SO --> PRISMA
    SO --> CLI
    SO --> VEH
